Build pepabo engage page
canonical-web-and-design/jp.ubuntu.com pull request #238
Opened 2020-09-29 11:43 UTC by bethcollins92

## Done

- Build engage page at `/engage/case-study-gmo-pepabo`
- Add to `/engage/index.html`
- Create [social banner](https://assets.ubuntu.com/v1/528cf2ab-facebook_and_linkedin_banner+%283%29.jpeg) 

## QA

- Check out this feature branch
- Run the site using the command ./run serve or dotrun
- View the site locally in your web browser at: [http://0.0.0.0:8012/engage](http://0.0.0.0:8012/engage) to check GMO pepabo added and check engage page at [http://0.0.0.0:8012/engage/case-study-gmo-pepabo](http://0.0.0.0:8012/engage/case-study-gmo-pepabo) matches [copy doc](https://docs.google.com/document/d/1TewivXyiRIQyz8m4IXg1o1gC7nsZAxrfcrB32szE8jI/edit#) and [design](https://github.com/canonical-web-and-design/web-squad/issues/3055)

## Issue / Card

Fixes [#8363](https://github.com/canonical-web-and-design/ubuntu.com/issues/8363)

2020-09-29 11:43 UTC, webteam-app commented
Demo starting at https://jp-ubuntu-com-238.demos.haus

2020-09-30 08:39 UTC, SirSamTumless commented
Waiting on PDF

2020-09-30 08:55 UTC, sowasred2012 requested changes
LGTM, just a missing meta image

2020-09-30 08:55 UTC, sowasred2012 commented on templates/engage/case-study-gmo-pepabo.html
> +{% block meta_image %}{% endblock %}
This is missing the meta image given [here](https://github.com/canonical-web-and-design/web-squad/issues/3055#issuecomment-676479694) - you may need to upload it to the asset manager, not sure if it already has been.

2020-10-05 11:08 UTC, sowasred2012 approved these changes
LGTM!

2020-10-05 14:02 UTC, merged

2020-10-05 15:12 UTC, AmberCharitos commented
@SirSamTumless @bethcollins92 the brief was for this engage page to also be in Japanese - it looks as though it is in English - [here](https://docs.google.com/document/d/1TewivXyiRIQyz8m4IXg1o1gC7nsZAxrfcrB32szE8jI/edit) is the copy doc for the Japanese version of the landing page

2020-10-05 15:37 UTC, SirSamTumless commented
@AmberCharitos It is in jP?

2020-10-05 15:44 UTC, AmberCharitos commented
@SirSamTumless my browser auto translated to English (wow that was silly of me) - sorry had a moment - thank you!!

2020-10-06 08:19 UTC, AmberCharitos commented
@bethcollins92 @SirSamTumless, we've had some edits requested from GMO Pepabo on this page.
 
1) An update to the first paragraph on the engage page - updated in [this](https://docs.google.com/document/d/1TewivXyiRIQyz8m4IXg1o1gC7nsZAxrfcrB32szE8jI/edit#) doc 
2) The logo used has been changed colour and they would like it updated to one including their brand colouring - I am waiting for them to send me a copy of this logo with a black background. This is something they would also like changed in the uk version. 
3) The quote that is pulled out has been cut with the orange close bracket - could this be shifted so as not to obscure the text? 

Sorry for all this!