WIP - Update marketo endpoint
canonical-web-and-design/jp.ubuntu.com pull request #370
Opened 2022-01-07 11:28 UTC by minkyngkm

## Done

[List of work items including drive-bys]

## QA

[List of steps to QA the new features or prove the bug has been resolved]

## Issue / Card

[List of links to Github issues/bugs and cards if needed - e.g. `Fixes #1`]

## Screenshots

[if relevant, include a screenshot]

2022-01-07 11:28 UTC, webteam-app commented
Demo starting at https://jp-ubuntu-com-370.demos.haus

2022-01-13 11:34 UTC, anthonydillon requested changes
I don't think we need form-validation.js anymore?

2022-01-14 10:08 UTC, anthonydillon approved these changes
One small comment and still can't see them submissions in the campaign but I assume that is due to some internal logic. There are no errors in sentry or in QA so :+1: once emails have the pattern attr.

2022-01-17 16:31 UTC, minkyngkm commented
QA completed! 
![image](https://user-images.githubusercontent.com/57550290/149807053-362d5523-5fdd-45b3-bb77-16bec747b6bd.png)

2022-01-17 16:31 UTC, merged